server:
  port: 9082

spring:
  datasource:
    druid:
      url: jdbc:postgresql://172.16.99.43:5432/dapu
      username: dapuprod
      password: dapuprodgrowth123

  redis:
    # Redis数据库索引（默认为0）
    database: 14
    # Redis服务器地址
    host: 172.16.99.43
    # Redis服务器连接端口
    port: 6019
    # Redis 密码
    password: aFoT0Ny$Py63BTvU

sys:
  # 是否开启对thrift接口连通性的检测
  validateThrift: false
  #当前应用名称
  projectName: dapu-operate-prod
  #服务平台地址
  smpDomain: http://smp.growth-master.com
  #是否开启错误日志上报
  openExceptionNotice: true
shiro:
  # 登录 url
  loginUrl: http://dapu.growth-master.com/login
  # 登录成功后跳转的 url
  successUrl: http://dapu.growth-master.com/main
  # 登出 url
  logoutUrl: http://dapu.growth-master.com/logout
  #强制修改密码的url
  resetPasswordUrl: http://dapu.growth-master.com/resetPass
  #设置cookie所在的域名
  cookieDomain: dapu.growth-master.com

thrift:
  server:
    host: 172.16.99.43
    port: 7777
