server:
  port: 9094

spring:
  datasource:
    druid:
      url: jdbc:postgresql://39.98.78.201:5432/dapu_test?currentSchema=dapu_test
      username: dapu_test
      password: daputest123

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:

sys:
  # 是否开启对thrift接口连通性的检测
  validateThrift: false
  #当前应用名称
  projectName: dapu-operate-prod
  #服务平台地址
  smpDomain: http://smp.growth-master.com
  #是否开启错误日志上报
  openExceptionNotice: false

shiro:
  # 登录 url
  loginUrl: http://localhost:9091/login
  # 登录成功后跳转的 url
  successUrl: http://localhost:9091/main
  # 登出 url
  logoutUrl: http://localhost:9091/logout
  #强制修改密码的url
  resetPasswordUrl: http://localhost:9091/resetPass
  #设置cookie所在的域名，所有业务子系统必须和权限管理系统配置一致方可共享session
  cookieDomain: localhost

thrift:
  server:
    host: 39.100.145.35
    port: 7777
