server:
  port: 80
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      username: gimspromote
      password: gimsdemodb123
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.linksteady.servie.*

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/actuator/*'

      # StatViewServlet配置 
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123!@#
        # IP白名单
        # allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6376
    # Redis 密码
    password: growthmaster666
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 200

  thymeleaf:
    cache: false

  aop:
    proxy-target-class: true
  cache:
    type:
      redis

  resources:
    chain:
      strategy:
        fixed:
          enabled: true
          paths: /js/**, /v1.0.0/**
          version: v1.0.0

#  devtools:
#    livereload:
#      enabled: true #是否支持livereload
#      port: 35729
#    restart:
#      enabled: true #是否支持热部署

info:
  app:
    name: "UOMS"
    description: "link steady 智能增长平台"
    version: "2.0"
    spring-boot-version: "2.0.4.RELEASE"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
# spring boot admin配置结束
jasypt:
  encryptor:
    password: linksteady

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.linksteady.system.domain, com.linksteady.operate.domain
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  property:
    order: BEFORE
  configuration:
    # 注意这里需要加单引号
    jdbc-type-for-null: 'null'

#mappers 多个接口时逗号隔开
mapper:
  mappers: com.linksteady.common.config.MyMapper
  not-empty: false
  identity: oracle
  order: after

#pagehelper
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      linksteady:
        common:
          dao: debug
        operate:
          dao: debug


# system 配置
sys:
  shiro:
    # shiro redis缓存时长，默认1800秒
    expireIn: 1800
    # session 超时时间，默认1800000毫秒
    sessionTimeout: 1800000
    # rememberMe cookie有效时长，默认86400秒，即一天
    cookieTimeout: 86400
    # 免认证的路径配置，如静态资源，druid监控页面，注册页面，验证码请求等
    anonUrl: /css/**,/js/**,/fonts/**,/img/**,/images/**,/druid/**,/user/regist,/gifCode,/,/actuator/**,/test/**
    # 登录 url
    loginUrl: /login
    # 登录成功后跳转的 url
    successUrl: /page/index
    # 登出 url
    logoutUrl: /logout
    # 未授权跳转 url
    unauthorizedUrl: /403
  # 时间类型参数在前端页面的展示格式，默认格式为 yyyy-MM-dd HH:mm:ss
  timeFormat: yyyy-MM-dd HH:mm:ss
  # 是否开启 AOP 日志，默认开启
  openAopLog: false