server:
  port: 9091

spring:
  datasource:
    druid:
      url: jdbc:postgresql://127.0.0.1:5432/dapu_test?currentSchema=dapu_test
      username: dapu_test
      password: daputest123

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:

# system 配置
sys:
  # 是否开启对thrift接口连通性的检测
  validateThrift: false
  #当前应用名称
  projectName: dapu-system-dev
  #服务平台地址
  smpDomain: http://localhost:9063
  #是否开启错误日志上报
  openExceptionNotice: false

#权限相关配置
shiro:
  # 登录 url
  loginUrl: /login
  # 登录成功后跳转的 url
  successUrl: /main
  # 登出 url
  logoutUrl: /logout
  #强制修改密码的url
  resetPasswordUrl: /resetPass
  #设置cookie所在的域名，所有业务子系统必须和权限管理系统配置一致方可共享session
  cookieDomain: localhost

logging:
  level:
    com.linksteady.system.dao: debug

