spring:
  datasource:
    druid:
      url: jdbc:postgresql://127.0.0.1:5432/dapu_test?currentSchema=dapu_test
      username: dapu_test
      password: daputest123

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:

sys:
  #当前应用名称
  projectName: qywxApi-dev
  #服务平台地址
  smpDomain: http://localhost:9063
  #是否开启错误日志上报
  openExceptionNotice: false
  #是否是演示环境
  demoEnvironment: false
  # 是否开启 AOP 日志，默认开启
  openAopLog: true
  #thrift服务的参数
  thriftServerHost: 192.168.0.116
  thriftServerPort: 7778

shiro:
  # shiro redis缓存时长，默认1800秒  7200
  expireIn: 1800
  # session 超时时间，默认1800000毫秒 7200000
  sessionTimeout: 1800000
  # rememberMe cookie有效时长，默认86400秒，即一天
  cookieTimeout: 86400
  # 免认证的路径配置，如静态资源，druid监控页面，注册页面，验证码请求等
  anonUrl: /smpclient/**,/plugins/**,/**/css/**,/**/js/**,/**/fonts/**,/img/**,/images/**,/druid/**,/actuator/**,/test/**,/qw/**,/login,/gifCode,/contractEvent/**,/api/**
  #首次登陆是否强制要求修改密码
  allowResetPassword: false
  # 未授权跳转 url
  unauthorizedUrl: /403
  # 登录 url
  loginUrl: http://localhost:9091/login
  # 登录成功后跳转的 url
  successUrl: http://localhost:9091/main
  # 登出 url
  logoutUrl: http://localhost:9091/logout
  #强制修改密码的url
  resetPasswordUrl: http://localhost:9091/resetPass
  #设置cookie所在的域名，所有业务子系统必须和权限管理系统配置一致方可共享session
  cookieDomain: localhost

logging:
  level:
    com.linksteady.*.dao: debug