server:
  port: 9096

spring:
  datasource:
    druid:
      url: jdbc:postgresql://39.98.78.201:5432/dapu_test?currentSchema=dapu_test
      username: dapu_test
      password: daputest123

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password: