app:
  name: "UOMS"
  description: "link steady 诊断&运营系统"
  spring-boot-version: "2.0.4.RELEASE"
  version: @project.version@
  build:
    time: @timestamp@


server:
  port: 9092
  tomcat:
    uri-encoding: utf-8
spring:
  thymeleaf:
    cache: false

  aop:
    proxy-target-class: true
  cache:
    type:
      redis

  #MD5 方式请求静态资源
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /js/job/**, /css/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.linksteady.operate.domain
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  property:
    order: before
  configuration:
    # 注意这里需要加单引号
    jdbc-type-for-null: 'null'
    call-setters-on-nulls: true

#mappers 多个接口时逗号隔开
mapper:
  mappers: com.linksteady.operate.config.MyMapper
  not-empty: false
  identity: oracle
  order: before

#pagehelper
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      linksteady:
        operate:
          dao: info

sys:
  job:
    token: LINKSTEADY  #和调度中心通信校验用的token
    callbackUrl: http://job.growth-master.com/api/jobcallback   #回写任务状态的回调地址
    jobrewriteUrl: http://job.growth-master.com//api/jobrewrite  #回写任务执行日志的地址
  shiro:
    # shiro redis缓存时长，默认1800秒
    expireIn: 7200
    # session 超时时间，默认1800000毫秒
    sessionTimeout: 7200000
    # rememberMe cookie有效时长，默认86400秒，即一天
    cookieTimeout: 86400
    # 免认证的路径配置，如静态资源，druid监控页面，注册页面，验证码请求等
    anonUrl: /job/**,/api/**,/plugins/**,/**/css/**,/**/js/**,/**/fonts/**,/img/**,/images/**,/druid/**,/,/actuator/**,/test/**,/sysinfo
    # 登录 url
    loginUrl: http://dev.growth-master.com/login
    # 登录成功后跳转的 url
    successUrl: http://dev.growth-master.com/main
    # 登出 url
    logoutUrl: http://dev.growth-master.com/logout
    # 未授权跳转 url
    unauthorizedUrl: /403
    #强制修改密码的url
    resetPasswordUrl: http://dev.growth-master.com/resetPass
    #首次登陆是否强制要求修改密码
    allowResetPassword: false
    #设置cookie所在的域名，所有业务子系统必须和权限管理系统配置一致方可共享session
    cookieDomain: dev.growth-master.com

thrift:
  server:
    host: 127.0.0.1
    port: 9996